### ISSUE TITLE
travis-ci/travis-ci/issues/1235

### ISSUE THREAD

**Issue by zbeekman** [krlmlr-archive/texlive-squashfs#1]
I found this from: travis-ci/travis-ci/issues/1235 because I am interested in using travis-ci for testing/building LaTeX documents…

I’m wondering if I can just use [.travis.yml](../blob/master/.travis.yml) (plus some extra stuff to build it using CMake, makefiles, etc.) to accomplish the build with your texlive tarball faster than the usual apt-get rigamarole?

**Comment by krlmlr** [comment]
Download + untar (especially if done simultaneously) might be a tad faster than installing via `apt-get`, but I think you just have to see for yourself if this is worthwhile for you. The tarball in this repo containls only a tiny subset of TeXlive.

**Comment by zbeekman** [comment]
Ah, I see... So the strategy is to use just the parts you need of texlive... Package them up, then download and extract them to do the build. Any tips on figuring out what parts of texlive a particular project requires?

**Comment by krlmlr** [comment]
Sorry, I don't have anything better than "try and error" for this...

**Comment by zbeekman** [comment]
well thanks for getting us this far :smiley:
